### PR TITLE
set `#![no_std]`

### PR DESCRIPTION
**Pull request by FrozenDroid**
I don't see a reason not to, and then this crate will work on embedded projects :)

### CODE REVIEW

**Comment by cjriches** [comment]
Did you test this? I get the following on your branch when running `cargo test`:
```
error[E0412]: cannot find type `String` in this scope
  --> serde_unit_struct/src/lib.rs:20:37
   |
20 |     #[derive(Serialize_unit_struct, Deserialize_unit_struct)]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

You'll notice that the `Deserialize` impl uses the `String` type; my understanding is that this requires `std`. I think this can be trivially fixed by the following diff:
```
     let deserialize_impl = quote! {
         impl<'de> serde::Deserialize<'de> for #name {
             fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
-                <String as serde::Deserialize>::deserialize(deserializer)
+                <&str as serde::Deserialize>::deserialize(deserializer)
                     .and_then(|s| {
-                        if &s == #name_str {
+                        if s == #name_str {
                             Ok(Self)
                         } else {
                             Err(serde::de::Error::custom(#error_msg))
```

**Comment by FrozenDroid** [comment]
@cjriches Thanks for the quick reply!
Yeah, you're exactly right. Sorry about that, I should've run `cargo test` before committing!
I've implemented your diff, and the tests now pass, and it seems to compile just fine on my `#![no_std]` project.

**Review by cjriches — APPROVED** [review]
Thanks!

**Comment by cjriches** [comment]
Merged and released as `v0.1.2`.

**Pull request merged**
